name: Accessibility 2

# **What it does**: Regularly audits API links in our documentation.
# **Why we have it**: It's too burdensome to check on every commit like we do for internal links.
# **Who does it impact**: PCX team

on:
  pull_request:
    branches:
      - production

jobs:
  test2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - uses: a11ywatch/github-action@v2
        with:
          WEBSITE_URL: https://developers.cloudflare.com
          SUBDOMAINS: false
          TLD: false
          SITEMAP: true
          FAIL_ERRORS_COUNT: 15
          LIST: true
          FIX: false
          UPGRADE: false
