name: Accessibility 2

# **What it does**: Regularly audits API links in our documentation.
# **Why we have it**: It's too burdensome to check on every commit like we do for internal links.
# **Who does it impact**: PCX team

on:
  pull_request:
    branches:
      - production

jobs:
  test2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libgbm-dev
          sudo apt-get install xvfb
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1
      
      - name: Install npm packages
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Accessibility Audits
        run: |
          npm install -g @jakepartusch/lumberjack
          xvfb-run --auto-servernum lumberjack --url https://developers.cloduflare.com
