name: Accessibility

# **What it does**: Regularly audits API links in our documentation.
# **Why we have it**: It's too burdensome to check on every commit like we do for internal links.
# **Who does it impact**: PCX team

on:
  pull_request:
    branches:
      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1
      
      - name: Install dependencies
        run: npm install @actions/core pa11y puppeteer

      - name: Run accessibility test
        id: test-accessibility
        run: npm run test-accessibility
