name: PR Opened

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
on:
  pull_request:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  assign:
    name: CODEOWNERS action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v29.0.3

      - uses: austenstone/codeowners-coverage@main
        with:
          ignore-default: 'true'
          files: ${{ steps.changed-files.outputs.all_changed_files }}

            
            