name: PR Opened

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
on:
  pull_request:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  assign:
    name: CODEOWNERS action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: codeowners
        uses: SvanBoxel/codeowners-action@2.1
        with: 
          file_match_info: 'true'

      - name: Output
        run: echo ${{ steps.codeowners.outputs.codeowners }}

            
            