name: PR Opened

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
on:
  pull_request:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  assign:
    id: codeowners
    name: CODEOWNERS action
    uses: SvanBoxel/codeowners-action@2.1
  - run: |
      echo ${{ steps.codeowners.outputs.codeowners }};
            
            